#!/bin/bash

Black() { echo "\e[30m$1\e[0m"; }
Red() { echo "\e[31m$1\e[0m"; }
Green() { echo "\e[32m$1\e[0m"; }
Yellow() { echo "\e[33m$1\e[0m"; }
Blue() { echo "\e[34m$1\e[0m"; }
Purple() { echo "\e[35m$1\e[0m"; }
SkyBlue() { echo "\e[36m$1\e[0m"; }
White() { echo "\e[37m$1\e[0m"; }
